In [7]:
import numpy as np
np.random.seed(16)
random_integers = np.random.randint(1,high=10000, size=(20, 5))
print(random_integers)

[[6826 2170  582 1346  636]
 [4549  382  773 5418 5601]
 [7057 3449 5435 3951 4499]
 [5749 6305 7968 3659 1743]
 [4702 4302  797 5235 3516]
 [ 749 4105 3043 2194 2345]
 [4277 8320  365  527  439]
 [7407 5999 7465 6573 6929]
 [6583 8982 1685 8890  813]
 [ 147 5465 6252 6776 1474]
 [1788 4012  263 2194  781]
 [3458 8388 3421 4594   24]
 [ 967 1466 2327 4415 9500]
 [1492 3589 6787 5497 1066]
 [5360 7149 4188 6388 4971]
 [ 876 4247 5313 6138 8829]
 [9303 2670 8163 5764 9327]
 [8614 3986 5859 9045 6108]
 [7307 7642 4709 8336 6854]
 [ 412 6330 6261 7218 4460]]


In [34]:
#Display maximum value
np.max(random_integers)

9500

In [35]:
#Display minimum value
np.min(random_integers)

24

In [27]:
#Display a slice of first 3 rows
df = pd.DataFrame(random_integers)
first_3_rows = df.head(3)
print(first_3_rows)

      0     1     2     3     4
0  6826  2170   582  1346   636
1  4549   382   773  5418  5601
2  7057  3449  5435  3951  4499


In [26]:
#Display a slice of last 3 rows
df = pd.DataFrame(random_integers)
last_3_rows = df.tail(3)
print(last_3_rows)

       0     1     2     3     4
17  8614  3986  5859  9045  6108
18  7307  7642  4709  8336  6854
19   412  6330  6261  7218  4460


In [41]:
#Display a slice of last 2 columns

last_2_columns = np.array(random_integers)
last_2_columns[:,-2:]

array([[1346,  636],
       [5418, 5601],
       [3951, 4499],
       [3659, 1743],
       [5235, 3516],
       [2194, 2345],
       [ 527,  439],
       [6573, 6929],
       [8890,  813],
       [6776, 1474],
       [2194,  781],
       [4594,   24],
       [4415, 9500],
       [5497, 1066],
       [6388, 4971],
       [6138, 8829],
       [5764, 9327],
       [9045, 6108],
       [8336, 6854],
       [7218, 4460]])

In [78]:
#Values of 3rd to 4th column in rows 11 and 12
df = pd.DataFrame(random_integers)
df.iloc[[11,12],[3,4]]

3     4
11  4594    24
12  4415  9500

In [71]:
#sort the values from the smallest to highest
np.sort(random_integers)

array([[ 582,  636, 1346, 2170, 6826],
       [ 382,  773, 4549, 5418, 5601],
       [3449, 3951, 4499, 5435, 7057],
       [1743, 3659, 5749, 6305, 7968],
       [ 797, 3516, 4302, 4702, 5235],
       [ 749, 2194, 2345, 3043, 4105],
       [ 365,  439,  527, 4277, 8320],
       [5999, 6573, 6929, 7407, 7465],
       [ 813, 1685, 6583, 8890, 8982],
       [ 147, 1474, 5465, 6252, 6776],
       [ 263,  781, 1788, 2194, 4012],
       [  24, 3421, 3458, 4594, 8388],
       [ 967, 1466, 2327, 4415, 9500],
       [1066, 1492, 3589, 5497, 6787],
       [4188, 4971, 5360, 6388, 7149],
       [ 876, 4247, 5313, 6138, 8829],
       [2670, 5764, 8163, 9303, 9327],
       [3986, 5859, 6108, 8614, 9045],
       [4709, 6854, 7307, 7642, 8336],
       [ 412, 4460, 6261, 6330, 7218]])

In [48]:
#Calculate the average value by column
df = pd.DataFrame(random_integers)
Average = df.mean()
print(Average)

0    4381.15
1    4947.90
2    4082.80
3    5207.90
4    3995.75
dtype: float64


In [52]:
#Calculate the average value by rows
df = pd.DataFrame(random_integers)
Average = df.mean(axis=1)
print(Average)

0     2312.0
1     3344.6
2     4878.2
3     5084.8
4     3710.4
5     2487.2
6     2785.6
7     6874.6
8     5390.6
9     4022.8
10    1807.6
11    3977.0
12    3735.0
13    3686.2
14    5611.2
15    5080.6
16    7045.4
17    6722.4
18    6969.6
19    4936.2
dtype: float64


In [64]:
#Create a list and populate with values of the second column
import numpy as np

arr = np.array(random_integers)

print(f'NumPy Array:\n{arr}')

random_integers_list = arr.tolist()


NumPy Array:
[[6826 2170  582 1346  636]
 [4549  382  773 5418 5601]
 [7057 3449 5435 3951 4499]
 [5749 6305 7968 3659 1743]
 [4702 4302  797 5235 3516]
 [ 749 4105 3043 2194 2345]
 [4277 8320  365  527  439]
 [7407 5999 7465 6573 6929]
 [6583 8982 1685 8890  813]
 [ 147 5465 6252 6776 1474]
 [1788 4012  263 2194  781]
 [3458 8388 3421 4594   24]
 [ 967 1466 2327 4415 9500]
 [1492 3589 6787 5497 1066]
 [5360 7149 4188 6388 4971]
 [ 876 4247 5313 6138 8829]
 [9303 2670 8163 5764 9327]
 [8614 3986 5859 9045 6108]
 [7307 7642 4709 8336 6854]
 [ 412 6330 6261 7218 4460]]


In [105]:
#Output the elements in the list created

df[1].values

array([2170,  382, 3449, 6305, 4302, 4105, 8320, 5999, 8982, 5465, 4012,
       8388, 1466, 3589, 7149, 4247, 2670, 3986, 7642, 6330])

In [67]:
#use boolean operations to output elements greater than 5000
print (random_integers>5000)

[[ True False False False False]
 [False False False  True  True]
 [ True False  True False False]
 [ True  True  True False False]
 [False False False  True False]
 [False False False False False]
 [False  True False False False]
 [ True  True  True  True  True]
 [ True  True False  True False]
 [False  True  True  True False]
 [False False False False False]
 [False  True False False False]
 [False False False False  True]
 [False False  True  True False]
 [ True  True False  True False]
 [False False  True  True  True]
 [ True False  True  True  True]
 [ True False  True  True  True]
 [ True  True False  True  True]
 [False  True  True  True False]]
